name: FPL Transfers and Price Change

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 min (UTC)
  workflow_dispatch:      # allow manual trigger from GitHub UI

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scripts
        run: |
          python track_transfers.py
          python analyze_transfers.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add fpl_transfers_log.csv fpl_predictions_log.csv fpl_summary.csv
          git commit -m "Update logs [skip ci]" || echo "No changes to commit"
          git push
